Resources:
  RealiumUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      BillingMode: PROVISIONED
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: realium-users

  RealiumPropertiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: propertyId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      BillingMode: PROVISIONED
      KeySchema:
        - AttributeName: propertyId
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: realium-properties

Outputs:
  RealiumUsersTableArn:
    Description: Realium Users Table ARN
    Value: !GetAtt RealiumUsersTable.Arn
    Export:
      Name: RealiumUsersTableArn
  RealiumPropertiesTableArn:
    Description: Realium Properties Table ARN
    Value: !GetAtt RealiumPropertiesTable.Arn
    Export:
      Name: RealiumPropertiesTableArn
