Resources:
  RealiumUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: RealiumUserPool
      AutoVerifiedAttributes:
        - email
      EmailVerificationMessage: Your Realium verification code is {####}.
      EmailVerificationSubject: Realium Verification Code
      MfaConfiguration: OPTIONAL
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
          TemporaryPasswordValidityDays: 7
      Schema:
        - Name: email
          Mutable: false
          Required: true
        - Name: given_name
          Mutable: true
          Required: true
        - Name: family_name
          Mutable: true
          Required: true
        - Name: phone_number
          Mutable: true
          Required: false
        - Name: address
          Mutable: true
          Required: false
        - Name: wallet
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: country
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: city
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: state
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: postal_code
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: pref_email
          AttributeDataType: Boolean
          Mutable: true
          Required: false
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false

  RealiumUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref RealiumUserPool
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      CallbackURLs:
        - http://localhost:3000/*
        - https://realium.net/*
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH

  RealiumAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: Group for internal admins and access
      GroupName: Admin
      Precedence: 0
      UserPoolId: !Ref RealiumUserPool

Outputs:
  UserPoolId:
    Description: UserPoolID for Realium
    Value: !Ref RealiumUserPool
    Export:
      Name: RealiumUserPoolId
  UserPoolClientId:
    Description: UserPoolClientID for Realium
    Value: !Ref RealiumUserPoolClient
    Export:
      Name: RealiumUserPoolClientId
