Parameters:
  AppName:
    Type: String
    Description: Base url without https:// and without www
    Default: realium
  DomainName:
    Type: String
    Description: Base url without https:// and without www. Should exist in Route53
    Default: realium.net
  GithubRepo:
    Type: String
    Description: Http url to github repo
    Default: https://github.com/Blockchain-for-Real-Estate/realium-web.git
  GithubAccessToken:
    Type: String
    Description: PAT from github to allow this app to setup with the repo
    NoEcho: true

Resources:
  App:
    Type: AWS::Amplify::App
    Properties:
      Name: !Ref AppName
      Description: Front end hosting for nextjs project
      IAMServiceRole: !ImportValue RealiumAppRoleArn
      OauthToken: !Ref GithubAccessToken
      Repository: !Ref GithubRepo
      EnvironmentVariables:
        - Name: _LIVE_UPDATES
          Value: '[{ "pkg": "next-version", "type": "internal", "version": "10" }]'
      CustomRules:
        - Source: /<*>
          Target: /index.html
          Status: 404-200
        - Source: !Join ["", ["https://", !Ref DomainName]]
          Target: !Join ["", ["https://www.", !Ref DomainName]]
          Status: "200"
      Tags:
        - Key: App
          Value: !Ref AppName
      BuildSpec: |-
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - npm ci
            build:
              commands:
                - npm run build
          artifacts:
            baseDirectory: .next
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*

  AppBranchProd:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt App.AppId
      BranchName: main
      Description: Production branch of the repository
      EnableAutoBuild: True
      EnablePerformanceMode: False
      EnablePullRequestPreview: True
      EnvironmentVariables:
        - Name: ENV_NAME
          Value: prod
      Stage: PRODUCTION
      Tags:
        - Key: App
          Value: !Ref AppName

  AppBranchDev:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt App.AppId
      BranchName: develop
      Description: Development branch of the repository
      EnableAutoBuild: True
      EnablePerformanceMode: False
      EnablePullRequestPreview: True
      EnvironmentVariables:
        - Name: ENV_NAME
          Value: develop
      Stage: DEVELOPMENT
      Tags:
        - Key: App
          Value: !Ref AppName

  AppDomainName:
    Type: AWS::Amplify::Domain
    Properties:
      AppId: !GetAtt App.AppId
      DomainName: !Ref DomainName
      SubDomainSettings:
        - BranchName: !GetAtt AppBranchProd.BranchName
          Prefix: ""
        - BranchName: !GetAtt AppBranchProd.BranchName
          Prefix: www
        - BranchName: !GetAtt AppBranchDev.BranchName
          Prefix: develop
