Parameters:
  AppName:
    Type: String
    Description: Base url without https:// and without www
    Default: realium
  DomainName:
    Type: String
    Description: Base url without https:// and without www
    Default: realium.io
  GithubRepo:
    Type: String
    Description: Http url to github repo
    Default: https://github.com/Blockchain-for-Real-Estate/-web.git
  GithubAccessToken:
    Type: String
    Description: PAT from github to allow this app to setup with the repo

Resources:
  AppRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ["", [!Ref AppName, "AppRole"]]
      Description: Role for the frontend amplify app
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AdministratorAccess-Amplify
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess

  App:
    Type: AWS::Amplify::App
    Properties:
      Name: !Ref AppName
      Description: Front end hosting for nextjs project
      IAMServiceRole: !GetAtt AppRole.Arn
      OauthToken: !Ref GithubAccessToken
      Repository: !Ref GithubRepo
      EnvironmentVariables:
        - Name: _LIVE_UPDATES
          Value: '[{ "pkg": "next-version", "type": "internal", "version": "10" }]'
      CustomRules:
        - Source: /<*>
          Target: /index.html
          Status: 404-200
        - Source: !Join ["", ["https://", !Ref DomainName]]
          Target: !Join ["", ["https://www.", !Ref DomainName]]
          Status: "200"
      BuildSpec: |-
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - npm ci
            build:
              commands:
                - npm run build
          artifacts:
            baseDirectory: .next
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*

  AppBranchProd:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt App.AppId
      BranchName: main
      Description: Production branch of the repository
      EnableAutoBuild: True
      EnablePerformanceMode: False
      EnablePullRequestPreview: True
      EnvironmentVariables:
        - Name: ENV_NAME
          Value: prod
      Stage: PRODUCTION

  AppBranchDev:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt App.AppId
      BranchName: develop
      Description: develop branch of the repository
      EnableAutoBuild: True
      EnablePerformanceMode: False
      EnablePullRequestPreview: True
      EnvironmentVariables:
        - Name: ENV_NAME
          Value: develop
      Stage: DEVELOPMENT

  AppDomainName:
    Type: AWS::Amplify::Domain
    Properties:
      AppId: !GetAtt App.AppId
      DomainName: !Ref DomainName
      SubDomainSettings:
        - BranchName: !GetAtt AppBranchProd.BranchName
          Prefix: ""
        - BranchName: !GetAtt AppBranchProd.BranchName
          Prefix: www
        - BranchName: !GetAtt AppBranchDev.BranchName
          Prefix: develop
